package com.member.member.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.member.member.dto.MemberDto;

import java.math.BigDecimal;
import java.util.Date;

@Table(name = "sys_member")
public class MemberDomain extends MemberDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    @Column(id = "member_id",increment = true,length = 12,rule = "MB")
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_EMAIL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_TEL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private BigDecimal memberAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_HEADER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_SEX
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_AGE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_BIRTHDAY
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date memberBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.MEMBER_LOCK
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberLock;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_ID
     *
     * @return the value of sys_member.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_ID
     *
     * @param memberId the value for sys_member.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_NAME
     *
     * @return the value of sys_member.MEMBER_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_NAME
     *
     * @param memberName the value for sys_member.MEMBER_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_EMAIL
     *
     * @return the value of sys_member.MEMBER_EMAIL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_EMAIL
     *
     * @param memberEmail the value for sys_member.MEMBER_EMAIL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail == null ? null : memberEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_PASSWORD
     *
     * @return the value of sys_member.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberPassword() {
        return memberPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_PASSWORD
     *
     * @param memberPassword the value for sys_member.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword == null ? null : memberPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_TEL
     *
     * @return the value of sys_member.MEMBER_TEL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberTel() {
        return memberTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_TEL
     *
     * @param memberTel the value for sys_member.MEMBER_TEL
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberTel(String memberTel) {
        this.memberTel = memberTel == null ? null : memberTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_AMOUNT
     *
     * @return the value of sys_member.MEMBER_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public BigDecimal getMemberAmount() {
        return memberAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_AMOUNT
     *
     * @param memberAmount the value for sys_member.MEMBER_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberAmount(BigDecimal memberAmount) {
        this.memberAmount = memberAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_HEADER
     *
     * @return the value of sys_member.MEMBER_HEADER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberHeader() {
        return memberHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_HEADER
     *
     * @param memberHeader the value for sys_member.MEMBER_HEADER
     *
     * @mbg.generated Fri Jul 20 16:43:22 CST 2018
     */
    public void setMemberHeader(String memberHeader) {
        this.memberHeader = memberHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_SEX
     *
     * @return the value of sys_member.MEMBER_SEX
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberSex() {
        return memberSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_SEX
     *
     * @param memberSex the value for sys_member.MEMBER_SEX
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberSex(String memberSex) {
        this.memberSex = memberSex == null ? null : memberSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_AGE
     *
     * @return the value of sys_member.MEMBER_AGE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberAge() {
        return memberAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_AGE
     *
     * @param memberAge the value for sys_member.MEMBER_AGE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberAge(String memberAge) {
        this.memberAge = memberAge == null ? null : memberAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_BIRTHDAY
     *
     * @return the value of sys_member.MEMBER_BIRTHDAY
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getMemberBirthday() {
        return memberBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_BIRTHDAY
     *
     * @param memberBirthday the value for sys_member.MEMBER_BIRTHDAY
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberBirthday(Date memberBirthday) {
        this.memberBirthday = memberBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.MEMBER_BIRTHDAY
     *
     * @return the value of sys_member.MEMBER_LOCK
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberLock() {
        return memberLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.MEMBER_BIRTHDAY
     *
     * @param memberLock the value for sys_member.MEMBER_LOCK
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberLock(String memberLock) {
        this.memberLock = memberLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.CREATER
     *
     * @return the value of sys_member.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.CREATER
     *
     * @param creater the value for sys_member.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.CREATE_TIME
     *
     * @return the value of sys_member.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.CREATE_TIME
     *
     * @param createTime the value for sys_member.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.UPDATER
     *
     * @return the value of sys_member.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.UPDATER
     *
     * @param updater the value for sys_member.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.UPDATE_TIME
     *
     * @return the value of sys_member.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.UPDATE_TIME
     *
     * @param updateTime the value for sys_member.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}