package com.member.rule.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.member.rule.dto.RuleDto;

import java.math.BigDecimal;
import java.util.Date;

@Table(name = "sys_rule")
public class RuleDomain extends RuleDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.RULE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    @Column(id = "RULE_ID", increment = true, length = 12, rule = "RE")
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.RULE_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.RULE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private BigDecimal ruleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.RULE_NUMBER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String ruleNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.RULE_STATUS
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String ruleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rule.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.RULE_ID
     *
     * @return the value of sys_rule.RULE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.RULE_ID
     *
     * @param ruleId the value for sys_rule.RULE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.RULE_NAME
     *
     * @return the value of sys_rule.RULE_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.RULE_NAME
     *
     * @param ruleName the value for sys_rule.RULE_NAME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.RULE_AMOUNT
     *
     * @return the value of sys_rule.RULE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public BigDecimal getRuleAmount() {
        return ruleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.RULE_AMOUNT
     *
     * @param ruleAmount the value for sys_rule.RULE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setRuleAmount(BigDecimal ruleAmount) {
        this.ruleAmount = ruleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.RULE_NUMBER
     *
     * @return the value of sys_rule.RULE_NUMBER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getRuleNumber() {
        return ruleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.RULE_NUMBER
     *
     * @param ruleNumber the value for sys_rule.RULE_NUMBER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setRuleNumber(String ruleNumber) {
        this.ruleNumber = ruleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.RULE_NUMBER
     *
     * @return the value of sys_rule.RULE_STATUS
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getRuleStatus() {
        return ruleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.RULE_NUMBER
     *
     * @param ruleStatus the value for sys_rule.RULE_STATUS
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setRuleStatus(String ruleStatus) {
        this.ruleStatus = ruleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.CREATER
     *
     * @return the value of sys_rule.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.CREATER
     *
     * @param creater the value for sys_rule.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.CREATE_TIME
     *
     * @return the value of sys_rule.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.CREATE_TIME
     *
     * @param createTime the value for sys_rule.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.UPDATER
     *
     * @return the value of sys_rule.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.UPDATER
     *
     * @param updater the value for sys_rule.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rule.UPDATE_TIME
     *
     * @return the value of sys_rule.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rule.UPDATE_TIME
     *
     * @param updateTime the value for sys_rule.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}