package com.member.impulse.domain;

import com.easy.core.annotation.Column;
import com.easy.core.annotation.Table;
import com.member.impulse.dto.ImpulseDto;

import java.math.BigDecimal;
import java.util.Date;

@Table(name = "sys_impulse")
public class ImpulseDomain extends ImpulseDto{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.IMPULSE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    @Column(id = "IMPULSE_ID",increment = true,length = 12,rule = "IM")
    private String impulseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.IMPULSE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private BigDecimal impulseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.IMPULSE_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String impulseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.PAY_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_impulse.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.IMPULSE_ID
     *
     * @return the value of sys_impulse.IMPULSE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getImpulseId() {
        return impulseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.IMPULSE_ID
     *
     * @param impulseId the value for sys_impulse.IMPULSE_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setImpulseId(String impulseId) {
        this.impulseId = impulseId == null ? null : impulseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.MEMBER_ID
     *
     * @return the value of sys_impulse.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.MEMBER_ID
     *
     * @param memberId the value for sys_impulse.MEMBER_ID
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.IMPULSE_AMOUNT
     *
     * @return the value of sys_impulse.IMPULSE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public BigDecimal getImpulseAmount() {
        return impulseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.IMPULSE_AMOUNT
     *
     * @param impulseAmount the value for sys_impulse.IMPULSE_AMOUNT
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setImpulseAmount(BigDecimal impulseAmount) {
        this.impulseAmount = impulseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.IMPULSE_TYPE
     *
     * @return the value of sys_impulse.IMPULSE_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getImpulseType() {
        return impulseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.IMPULSE_TYPE
     *
     * @param impulseType the value for sys_impulse.IMPULSE_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setImpulseType(String impulseType) {
        this.impulseType = impulseType == null ? null : impulseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.PAY_TYPE
     *
     * @return the value of sys_impulse.PAY_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.PAY_TYPE
     *
     * @param payType the value for sys_impulse.PAY_TYPE
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.CREATER
     *
     * @return the value of sys_impulse.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.CREATER
     *
     * @param creater the value for sys_impulse.CREATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.CREATE_TIME
     *
     * @return the value of sys_impulse.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.CREATE_TIME
     *
     * @param createTime the value for sys_impulse.CREATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.UPDATER
     *
     * @return the value of sys_impulse.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.UPDATER
     *
     * @param updater the value for sys_impulse.UPDATER
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_impulse.UPDATE_TIME
     *
     * @return the value of sys_impulse.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_impulse.UPDATE_TIME
     *
     * @param updateTime the value for sys_impulse.UPDATE_TIME
     *
     * @mbg.generated Thu Jul 19 10:36:00 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}