server:
  port: 8085
  context-path: /
  token:
    timeout: 1200000
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver: com.mysql.jdbc.Driver
  application:
    name: member

profiles:
  active: member
  secret: 7786df7fc3a34e26a61c034d5ec8245d

config:
  auth: true
  filter: true
  filterUrl: /user/login,/user/getValidate,/member/saveMember,.js,.css,.png,.jpg,.html,.ico

translate:
  url: http://openapi.openspeech.cn/webapi/its.do
  appId: 5b2b6096
  apikey: d0c127d3ac5aa77e8af53d2a3e5c3cd5